package:
  name: xcast
  version: "0.6.9"

source:
  path: ../src

build:
  number: 0
  string: xcast
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - scipy
    - scikit-learn
    - xarray
    - dask
    - cartopy
    - matplotlib
    - statsmodels
    - pandas
    - numba
    - bottleneck

test:
  imports:
    - xcast
    - xcast.core
    - xcast.flat_estimators
    - xcast.estimators
    - xcast.preprocessing
    - xcast.validation
    - xcast.verification
    - xcast.visualization
about:
  home:
  license: MIT
  summary: "A Python Climate Forecasting Toolkit"
  description: "An Open-Source Python Climate Forecasting Toolkit"
  dev_url: https://github.com/kjhall01/xcast/
